### ISSUE TITLE
404 reports not uploading?

### ISSUE THREAD

**Issue by ktrue** [DShield-ISC/dshield#81]
I've noticed that I'm not getting any 404 reports on the dshield website, 

```Last Web Log Received:
Last 404 Log Received: 2017-08-25 01:30:04
Last ssh Log Received: 2017-09-22 18:47:23
Last ssh Firewall Log Received: 2017-09-22 19:00:30
Current Time/Date: 2017-09-22 19:26:31
```
I've done a git pull, sudo bin/install.sh with the latest version 2 days ago, but no 404 joy yet...

**Comment by jullrich** [comment]
do you see any evidence that the logs are being sent? (also checkind on the server)

**Comment by jullrich** [comment]
check if you have a "stuck" PID file (/var/run/weblogparser.pid ) and delete it. I am currently working on a check for this. But right now, if the file isn't deleted right, then the script will not run.

**Comment by ktrue** [comment]
on Dshield, I see the last submissions available were logged as

2017-08-20 34 reports for 3 URLs and nothing after that.

My status shows
```
Last Web Log Received:
Last 404 Log Received: 2017-08-25 01:30:04
Last ssh Log Received: 2017-09-24 19:46:07
Last ssh Firewall Log Received: 2017-09-24 20:00:45
Current Time/Date: 2017-09-24 20:18:03
```
so something happened between 8/20 and 2017-08-25 01:30:04 but I'd made no changes to the Honeypot then.  I did the update on 9/20 and it's still not working.

I just tried a manual submit:
```
pi@TRP2HP:/srv/dshield $ ls
dshield.pl  DShield.py  DShield.pyc  pifwparser.py  weblogsubmit.py
pi@TRP2HP:/srv/dshield $ sudo ./weblogsubmit.py
/etc/dshield.ini
{
	"type": "webhoneypot",
	"logs": [{
			"sip": "182.101.57.86",
			"url": "/",
			"headers": {
				"header_Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"header_Accept-Language": "zh-CN,zh;q=0.8",
				"header_Host": "24.5.140.48:7547",
				"header_Accept-Charset": "GBK,utf-8;q=0.7,*;q=0.3",
				"header_Accept-Encoding": "gzip,deflate,sdch",
				"header_User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1"
			},
			"time": 1506284431.05986,
			"useragent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1",
			"dip": "0.0.0.0",
			"method": "GET"
		}, {
			"sip": "182.101.57.86",
			"url": "/",
			"headers": {
				"header_Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"header_Accept-Language": "zh-CN,zh;q=0.8",
				"header_Host": "24.5.140.48:7547",
				"header_Accept-Charset": "GBK,utf-8;q=0.7,*;q=0.3",
				"header_Accept-Encoding": "gzip,deflate,sdch",
				"header_User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1"
			},
			"time": 1506284431.05986,
			"useragent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1",
			"dip": "0.0.0.0",
			"method": "GET"
		}, {
			"sip": "182.101.57.86",
			"url": "/",
			"headers": {
				"header_Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"header_Accept-Language": "zh-CN,zh;q=0.8",
				"header_Host": "24.5.140.48:7547",
				"header_Accept-Charset": "GBK,utf-8;q=0.7,*;q=0.3",
				"header_Accept-Encoding": "gzip,deflate,sdch",
				"header_User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1"
			},
			"time": 1506284431.05986,
			"useragent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1",
			"dip": "0.0.0.0",
			"method": "GET"
		}, {
			"sip": "182.101.57.86",
			"url": "/",
			"headers": {
				"header_Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"header_Accept-Language": "zh-CN,zh;q=0.8",
				"header_Host": "24.5.140.48:7547",
				"header_Accept-Charset": "GBK,utf-8;q=0.7,*;q=0.3",
				"header_Accept-Encoding": "gzip,deflate,sdch",
				"header_User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1"
			},
			"time": 1506284431.05986,
			"useragent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1",
			"dip": "0.0.0.0",
			"method": "GET"
		}, {
			"sip": "182.101.57.86",
			"url": "/",
			"headers": {
				"header_Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
				"header_Accept-Language": "zh-CN,zh;q=0.8",
				"header_Host": "24.5.140.48:7547",
				"header_Accept-Charset": "GBK,utf-8;q=0.7,*;q=0.3",
				"header_Accept-Encoding": "gzip,deflate,sdch",
				"header_User-Agent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1"
			},
			"time": 1506284431.05986,
			"useragent": "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.1 (KHTML, like Gecko) Chrome/21.0.1180.89 Safari/537.1",
			"dip": "0.0.0.0",
			"method": "GET"
		}
	],
	"authheader": "ISC-HMAC-SHA256 Credentials=*redacted* Userid=1016656437 Nonce=*redacted*"
}
200
OK 3230 Bytes received
pi@TRP2HP:/srv/dshield $ sudo ~/dshield/bin/status.sh
API Key configuration ok
E-mail : kenmtrue@hotmail.com
API Key: b7e0b8c89d36b0d17845cd3c1ac85ea4e35f9550
User-ID: 1016656437
Last Web Log Received:
Last 404 Log Received: 2017-08-25 01:30:04
Last ssh Log Received: 2017-09-24 19:46:07
Last ssh Firewall Log Received: 2017-09-24 20:00:45
Current Time/Date: 2017-09-24 20:22:28
pi@TRP2HP:/srv/dshield $
```
And you can see the completion (200 code) but no ack in the bin/status.sh result ?!?

Very puzzled!

**Comment by jullrich** [comment]
ok. this is not the lock file issue. let me check on the server again.

**Comment by jullrich** [comment]
Can you take another look please? I think I fixed the issue

**Comment by ktrue** [comment]
I didn't find a lock file, but now the dropdown on the 404 page on Dshield shows data from 9-20 through 9-24 (today).

The bin/status.sh shows
```
Last Web Log Received:
Last 404 Log Received: 2017-08-25 01:30:04
Last ssh Log Received: 2017-09-24 21:45:48
Last ssh Firewall Log Received: 2017-09-24 21:30:06
Current Time/Date: 2017-09-24 21:46:12
```
so it may not be checking the right field/data as data is again showing on the Dshield 404 page...

**Comment by ktrue** [comment]
On the Dshield 404 page I see:

Last parsed submission: 2017-08-25 01:30:04 (Submissions are parsed twice an hour).

which matches the bin/status.sh output.  But... I'm seeing updates in the dropdown list for today
```
<option value="2017-09-24" selected="">2017-09-24: 47 reports 5 urls</option>
<option value="2017-09-23">2017-09-23: 57 reports 6 urls</option>
<option value="2017-09-22">2017-09-22: 68 reports 6 urls</option>
<option value="2017-09-21">2017-09-21: 45 reports 5 urls</option>
<option value="2017-09-20">2017-09-20: 76 reports 8 urls</option>
<option value="2017-09-19">2017-09-19: 13 reports 2 urls</option>
<option value="2017-08-20">2017-08-20: 34 reports 3 urls</option>
<option value="2017-08-19">2017-08-19: 77 reports 7 urls</option>
<option value="2017-08-18">2017-08-18: 43 reports 5 urls</option>
<option value="2017-08-17">2017-08-17: 62 reports 7 urls</option>
<option value="2017-08-16">2017-08-16: 46 reports 5 urls</option>
<option value="2017-08-15">2017-08-15: 90 reports 6 urls</option>
<option value="2017-08-14">2017-08-14: 58 reports 4 urls</option>
<option value="2017-08-13">2017-08-13: 77 reports 9 urls</option>
<option value="2017-08-12">2017-08-12: 60 reports 5 urls</option>
<option value="2017-08-11">2017-08-11: 85 reports 7 urls</option>
<option value="2017-08-10">2017-08-10: 57 reports 7 urls</option>
<option value="2017-08-09">2017-08-09: 60 reports 6 urls</option>
<option value="2017-08-08">2017-08-08: 56 reports 7 urls</option>
<option value="2017-08-07">2017-08-07: 57 reports 4 urls</option>
<option value="2017-08-06">2017-08-06: 71 reports 7 urls</option>
<option value="2017-08-05">2017-08-05: 67 reports 6 urls</option>
<option value="2017-08-04">2017-08-04: 70 reports 13 urls</option>
<option value="2017-08-03">2017-08-03: 51 reports 6 urls</option>
<option value="2017-08-02">2017-08-02: 70 reports 8 urls</option>
<option value="2017-08-01">2017-08-01: 47 reports 6 urls</option>
<option value="2017-07-31">2017-07-31: 68 reports 6 urls</option>
<option value="2017-07-30">2017-07-30: 66 reports 8 urls</option>
<option value="2017-07-29">2017-07-29: 68 reports 6 urls</option>
<option value="2017-07-28">2017-07-28: 28 reports 5 urls</option>
```

**Comment by ktrue** [comment]
Now it looks like the status is updating correctly.  sudo bin/status.sh shows
```
Last Web Log Received:
Last 404 Log Received: 2017-09-24 22:26:07
Last ssh Log Received: 2017-09-25 16:46:06
Last ssh Firewall Log Received: 2017-09-25 17:00:36
Current Time/Date: 2017-09-25 17:01:56
```

**Comment by ktrue** [comment]
Still an issue with the Dshield page -- the dropdown shows results (current), the status line remains with "Last 404 Log Received: 2017-09-24 22:26:07"

**Comment by ktrue** [comment]
Status still 'hung' for 404 logs:

```
Last Web Log Received:
Last 404 Log Received: 2017-09-24 22:26:07
Last ssh Log Received: 2017-10-11 01:45:57
Last ssh Firewall Log Received: 2017-10-11 02:00:28
Current Time/Date: 2017-10-11 02:19:07
```
Oddly enough, 2017-09-28 is the last date on the dropdown list on Dshield 404 reports page.

Something is still awry

**Comment by jullrich** [comment]
It looks like the date isn’t updated when ne data is imported. I guess I need to take another look at that script ☹

 

 

 

Johannes B. Ullrich, Ph.D., Dean of Research, SANS Technology Institute

SANS Cyber Defense Initiative 2017 returns to Washington DC, December 12-19. Choose from more than 35 hands-on Infosec courses plus bonus evening talks, vendor expo, and three challenging NetWars competitions including SANS’ 6th Annual Tournament of Champions! Learn more http://www.sans.org/u/vgX

**Comment by jullrich** [comment]
looks like your uploads stopped on the 28th. still can't find the problem why the "last submitted" date doesn't update properly. will dig into this a bit more.

**Comment by gebhard73** [comment]
current status for me:
- report overview correct (404 logs: 2017-10-13 13:15:04)
- infos on 404 page: 
  - Last parsed submission: 2017-10-13 13:15:04 (Submissions are parsed twice an hour).
BUT:
  - Total reports today: 0 
  - no details in table for today on 404 page

strange

**Comment by gebhard73** [comment]
can be closed from my perspective

**Comment by jullrich** [comment]
tracking this with issue #105
